#!/bin/sh
#
# @name X500 Double Coaxial (16 rotors)
#
# @type Custom Multicopter
# @class Copter
#
# Requires a PX4 firmware build with the CA rotor-count limit raised above
# 12. Geometry: two x500 chassis joined along body X, each arm carrying a
# counter-rotating coaxial pair. Motors 0-7 are the top layer, 8-15 the
# bottom layer; pair (n, n+8) is coaxial.

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_double_coax}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

# --- Control allocation: multicopter, 16 rotors -----------------------------
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 12


# Motor 0: A-FR top (CCW)
param set-default CA_ROTOR0_PX -0.3260
param set-default CA_ROTOR0_PY 0.1740
param set-default CA_ROTOR0_PZ -0.0600
param set-default CA_ROTOR0_AX 0.0
param set-default CA_ROTOR0_AY 0.0
param set-default CA_ROTOR0_AZ -1.0
# param set-default CA_ROTOR0_CT 8.55
param set-default CA_ROTOR0_KM +0.0500

# Motor 1: A-BL top (CCW)
param set-default CA_ROTOR1_PX -0.6740
param set-default CA_ROTOR1_PY -0.1740
param set-default CA_ROTOR1_PZ -0.0600
param set-default CA_ROTOR1_AX 0.0
param set-default CA_ROTOR1_AY 0.0
param set-default CA_ROTOR1_AZ -1.0
# param set-default CA_ROTOR1_CT 8.55
param set-default CA_ROTOR1_KM +0.0500

# Motor 2: A-FL top (CW)
param set-default CA_ROTOR2_PX -0.3260
param set-default CA_ROTOR2_PY -0.1740
param set-default CA_ROTOR2_PZ -0.0600
param set-default CA_ROTOR2_AX 0.0
param set-default CA_ROTOR2_AY 0.0
param set-default CA_ROTOR2_AZ -1.0
# param set-default CA_ROTOR2_CT 8.55
param set-default CA_ROTOR2_KM -0.0500

# Motor 3: A-BR top (CW)
param set-default CA_ROTOR3_PX -0.6740
param set-default CA_ROTOR3_PY 0.1740
param set-default CA_ROTOR3_PZ -0.0600
param set-default CA_ROTOR3_AX 0.0
param set-default CA_ROTOR3_AY 0.0
param set-default CA_ROTOR3_AZ -1.0
# param set-default CA_ROTOR3_CT 8.55
param set-default CA_ROTOR3_KM -0.0500

# Motor 4: B-FR top (CCW)
param set-default CA_ROTOR4_PX 0.6740
param set-default CA_ROTOR4_PY 0.1740
param set-default CA_ROTOR4_PZ -0.0600
param set-default CA_ROTOR4_AX 0.0
param set-default CA_ROTOR4_AY 0.0
param set-default CA_ROTOR4_AZ -1.0
# param set-default CA_ROTOR4_CT 8.55
param set-default CA_ROTOR4_KM +0.0500

# Motor 5: B-BL top (CCW)
param set-default CA_ROTOR5_PX 0.3260
param set-default CA_ROTOR5_PY -0.1740
param set-default CA_ROTOR5_PZ -0.0600
param set-default CA_ROTOR5_AX 0.0
param set-default CA_ROTOR5_AY 0.0
param set-default CA_ROTOR5_AZ -1.0
# param set-default CA_ROTOR5_CT 8.55
param set-default CA_ROTOR5_KM +0.0500

# Motor 6: B-FL top (CW)
param set-default CA_ROTOR6_PX 0.6740
param set-default CA_ROTOR6_PY -0.1740
param set-default CA_ROTOR6_PZ -0.0600
param set-default CA_ROTOR6_AX 0.0
param set-default CA_ROTOR6_AY 0.0
param set-default CA_ROTOR6_AZ -1.0
# param set-default CA_ROTOR6_CT 8.55
param set-default CA_ROTOR6_KM -0.0500

# Motor 7: B-BR top (CW)
param set-default CA_ROTOR7_PX 0.3260
param set-default CA_ROTOR7_PY 0.1740
param set-default CA_ROTOR7_PZ -0.0600
param set-default CA_ROTOR7_AX 0.0
param set-default CA_ROTOR7_AY 0.0
param set-default CA_ROTOR7_AZ -1.0
# param set-default CA_ROTOR7_CT 8.55
param set-default CA_ROTOR7_KM -0.0500

# Motor 8: A-FR bot (CW)
param set-default CA_ROTOR8_PX -0.3260
param set-default CA_ROTOR8_PY 0.1740
param set-default CA_ROTOR8_PZ 0.0600
param set-default CA_ROTOR8_AX 0.0
param set-default CA_ROTOR8_AY 0.0
param set-default CA_ROTOR8_AZ -1.0
# param set-default CA_ROTOR8_CT 8.55
param set-default CA_ROTOR8_KM -0.0500

# Motor 9: A-BL bot (CW)
param set-default CA_ROTOR9_PX -0.6740
param set-default CA_ROTOR9_PY -0.1740
param set-default CA_ROTOR9_PZ 0.0600
param set-default CA_ROTOR9_AX 0.0
param set-default CA_ROTOR9_AY 0.0
param set-default CA_ROTOR9_AZ -1.0
# param set-default CA_ROTOR9_CT 8.55
param set-default CA_ROTOR9_KM -0.0500

# Motor 10: A-FL bot (CCW)
param set-default CA_ROTOR10_PX -0.3260
param set-default CA_ROTOR10_PY -0.1740
param set-default CA_ROTOR10_PZ 0.0600
param set-default CA_ROTOR10_AX 0.0
param set-default CA_ROTOR10_AY 0.0
param set-default CA_ROTOR10_AZ -1.0
# param set-default CA_ROTOR10_CT 8.55
param set-default CA_ROTOR10_KM +0.0500

# Motor 11: A-BR bot (CCW)
param set-default CA_ROTOR11_PX -0.6740
param set-default CA_ROTOR11_PY 0.1740
param set-default CA_ROTOR11_PZ 0.0600
param set-default CA_ROTOR11_AX 0.0
param set-default CA_ROTOR11_AY 0.0
param set-default CA_ROTOR11_AZ -1.0
# param set-default CA_ROTOR11_CT 8.55
param set-default CA_ROTOR11_KM +0.0500
#
# # Motor 12: B-FR bot (CW)
# param set-default CA_ROTOR12_PX 0.6740
# param set-default CA_ROTOR12_PY 0.1740
# param set-default CA_ROTOR12_PZ 0.0600
# param set-default CA_ROTOR12_AX 0.0
# param set-default CA_ROTOR12_AY 0.0
# param set-default CA_ROTOR12_AZ -1.0
# # param set-default CA_ROTOR12_CT 8.55
# param set-default CA_ROTOR12_KM -0.0500
#
# # Motor 13: B-BL bot (CW)
# param set-default CA_ROTOR13_PX 0.3260
# param set-default CA_ROTOR13_PY -0.1740
# param set-default CA_ROTOR13_PZ 0.0600
# param set-default CA_ROTOR13_AX 0.0
# param set-default CA_ROTOR13_AY 0.0
# param set-default CA_ROTOR13_AZ -1.0
# param set-default CA_ROTOR13_CT 8.55
# param set-default CA_ROTOR13_KM -0.0500
#
# # Motor 14: B-FL bot (CCW)
# param set-default CA_ROTOR14_PX 0.6740
# param set-default CA_ROTOR14_PY -0.1740
# param set-default CA_ROTOR14_PZ 0.0600
# param set-default CA_ROTOR14_AX 0.0
# param set-default CA_ROTOR14_AY 0.0
# param set-default CA_ROTOR14_AZ -1.0
# param set-default CA_ROTOR14_CT 8.55
# param set-default CA_ROTOR14_KM +0.0500
#
# # Motor 15: B-BR bot (CCW)
# param set-default CA_ROTOR15_PX 0.3260
# param set-default CA_ROTOR15_PY 0.1740
# param set-default CA_ROTOR15_PZ 0.0600
# param set-default CA_ROTOR15_AX 0.0
# param set-default CA_ROTOR15_AY 0.0
# param set-default CA_ROTOR15_AZ -1.0
# param set-default CA_ROTOR15_CT 8.55
# param set-default CA_ROTOR15_KM +0.0500
#

# --- Output mapping: all 16 motors on the simulation actuator group ---------
# PX4 publishes actuator_motors to the gz topic /<model>/command/motor_speed;
# the MulticopterMotorModel plugins in the SDF subscribe by motorNumber.

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_FUNC8 108
param set-default SIM_GZ_EC_FUNC9 109
param set-default SIM_GZ_EC_FUNC10 110
param set-default SIM_GZ_EC_FUNC11 111
param set-default SIM_GZ_EC_FUNC12 112
# param set-default SIM_GZ_EC_FUNC13 113
# param set-default SIM_GZ_EC_FUNC14 114
# param set-default SIM_GZ_EC_FUNC15 115
# param set-default SIM_GZ_EC_FUNC16 116
#

# --- Minimum/maximum motor command bounds (normalised) ---------------------
param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MIN6 150
param set-default SIM_GZ_EC_MAX6 1000
param set-default SIM_GZ_EC_MIN7 150
param set-default SIM_GZ_EC_MAX7 1000
param set-default SIM_GZ_EC_MIN8 150
param set-default SIM_GZ_EC_MAX8 1000
param set-default SIM_GZ_EC_MIN9 150
param set-default SIM_GZ_EC_MAX9 1000
param set-default SIM_GZ_EC_MIN10 150
param set-default SIM_GZ_EC_MAX10 1000
param set-default SIM_GZ_EC_MIN11 150
param set-default SIM_GZ_EC_MAX11 1000
param set-default SIM_GZ_EC_MIN12 150
param set-default SIM_GZ_EC_MAX12 1000
# param set-default SIM_GZ_EC_MIN13 150
# param set-default SIM_GZ_EC_MAX13 1000
# param set-default SIM_GZ_EC_MIN14 150
# param set-default SIM_GZ_EC_MAX14 1000
# param set-default SIM_GZ_EC_MIN15 150
# param set-default SIM_GZ_EC_MAX15 1000
# param set-default SIM_GZ_EC_MIN16 150
# param set-default SIM_GZ_EC_MAX16 1000
#

# Increase the integral windup limit slightly to absorb modelling error on
# the large pitch inertia of the elongated platform.
param set-default MC_PITCHRATE_I 0.3
param set-default MC_ROLLRATE_I 0.2
